# Generated by Django 5.2.1 on 2025-05-26 11:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0008_alter_visitor_signout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='person_to_visit',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('check_in_time', models.DateTimeField(default=datetime.datetime.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('is_checked_in', models.BooleanField(default=True)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor.teacher'),
        ),
        migrations.DeleteModel(
            name='PersonToVisit',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
